import flags from "country-flag-icons/react/3x2";
const wikiHost = "https://upload.wikimedia.org/wikipedia/commons/thumb/";
export const ruIconsMap = {
  "RU-AMU": `${wikiHost}7/7a/Flag_of_Amur_Oblast.svg/100px-Flag_of_Amur_Oblast.svg.png`,
  "RU-ARK": `${wikiHost}1/16/Flag_of_Arkhangelsk_Oblast.svg/100px-Flag_of_Arkhangelsk_Oblast.svg.png`,
  "RU-AST": `${wikiHost}8/87/Flag_of_Astrakhan_Oblast.svg/100px-Flag_of_Astrakhan_Oblast.svg.png`,
  "RU-BEL": `${wikiHost}2/2b/Flag_of_Belgorod_Oblast.svg/100px-Flag_of_Belgorod_Oblast.svg.png`,
  "RU-BRY": `${wikiHost}2/2b/Flag_of_Bryansk_Oblast.svg/100px-Flag_of_Bryansk_Oblast.svg.png`,
  "RU-VLA": `${wikiHost}2/2d/Flag_of_Vladimir_Oblast.svg/100px-Flag_of_Vladimir_Oblast.svg.png`,
  "RU-VGG": `${wikiHost}3/35/Flag_of_Volgograd_Oblast.svg/100px-Flag_of_Volgograd_Oblast.svg.png`,
  "RU-VLG": `${wikiHost}a/af/Flag_of_Vologda_oblast.svg/100px-Flag_of_Vologda_oblast.svg.png`,
  "RU-VOR": `${wikiHost}6/64/Flag_of_Voronezh_Oblast.svg/100px-Flag_of_Voronezh_Oblast.svg.png`,
  "RU-IVA": `${wikiHost}5/5b/Flag_of_Ivanovo_Oblast.svg/100px-Flag_of_Ivanovo_Oblast.svg.png`,
  "RU-IRK": `${wikiHost}1/14/Flag_of_Irkutsk_Oblast.svg/100px-Flag_of_Irkutsk_Oblast.svg.png`,
  "RU-KGD": `${wikiHost}e/e4/Flag_of_Kaliningrad_Oblast.svg/100px-Flag_of_Kaliningrad_Oblast.svg.png`,
  "RU-KLU": `${wikiHost}e/ed/Flag_of_Kaluga_Oblast.svg/100px-Flag_of_Kaluga_Oblast.svg.png`,
  "RU-KEM": `${wikiHost}e/e3/Flag_of_Kemerovo_Oblast.svg/100px-Flag_of_Kemerovo_Oblast.svg.png`,
  "RU-KIR": `${wikiHost}4/41/Flag_of_Kirov_Oblast.svg/100px-Flag_of_Kirov_Oblast.svg.png`,
  "RU-KOS": `${wikiHost}2/2c/Flag_of_Kostroma_Oblast.svg/100px-Flag_of_Kostroma_Oblast.svg.png`,
  "RU-KGN": `${wikiHost}9/92/Flag_of_Kurgan_Oblast.svg/100px-Flag_of_Kurgan_Oblast.svg.png`,
  "RU-KRS": `${wikiHost}7/70/Flag_of_Kursk_Oblast.svg/100px-Flag_of_Kursk_Oblast.svg.png`,
  "RU-LEN": `${wikiHost}6/66/Flag_of_Leningrad_Oblast.svg/100px-Flag_of_Leningrad_Oblast.svg.png`,
  "RU-LIP": `${wikiHost}3/36/Flag_of_Lipetsk_Oblast.svg/100px-Flag_of_Lipetsk_Oblast.svg.png`,
  "RU-MAG": `${wikiHost}2/29/Flag_of_Magadan_Oblast.svg/100px-Flag_of_Magadan_Oblast.svg.png`,
  "RU-MOS": `${wikiHost}4/48/Flag_of_Moscow_oblast.svg/100px-Flag_of_Moscow_oblast.svg.png`,
  "RU-MUR": `${wikiHost}3/3b/Flag_of_Murmansk_Oblast.svg/100px-Flag_of_Murmansk_Oblast.svg.png`,
  "RU-NIZ": `${wikiHost}0/04/Flag_of_Nizhny_Novgorod_Region.svg/100px-Flag_of_Nizhny_Novgorod_Region.svg.png`,
  "RU-NGR": `${wikiHost}6/68/Flag_of_Novgorod_Oblast.svg/100px-Flag_of_Novgorod_Oblast.svg.png`,
  "RU-NVS": `${wikiHost}3/39/Flag_of_Novosibirsk_oblast.svg/100px-Flag_of_Novosibirsk_oblast.svg.png`,
  "RU-OMS": `${wikiHost}6/60/Flag_of_Omsk_Oblast.svg/100px-Flag_of_Omsk_Oblast.svg.png`,
  "RU-ORE": `${wikiHost}d/d6/Flag_of_Orenburg_Oblast.svg/100px-Flag_of_Orenburg_Oblast.svg.png`,
  "RU-ORL": `${wikiHost}0/05/Flag_of_Oryol_Oblast.svg/100px-Flag_of_Oryol_Oblast.svg.png`,
  "RU-PNZ": `${wikiHost}d/da/Flag_of_Penza_Oblast.svg/100px-Flag_of_Penza_Oblast.svg.png`,
  "RU-PSK": `${wikiHost}e/ef/Flag_of_Pskov_Oblast.svg/100px-Flag_of_Pskov_Oblast.svg.png`,
  "RU-ROS": `${wikiHost}d/d9/Flag_of_Rostov_Oblast.svg/100px-Flag_of_Rostov_Oblast.svg.png`,
  "RU-RYA": `${wikiHost}8/8c/Flag_of_Ryazan_Oblast.svg/100px-Flag_of_Ryazan_Oblast.svg.png`,
  "RU-SAM": `${wikiHost}1/13/Flag_of_Samara_Oblast.svg/100px-Flag_of_Samara_Oblast.svg.png`,
  "RU-SAR": `${wikiHost}f/f5/Flag_of_Saratov_Oblast.svg/100px-Flag_of_Saratov_Oblast.svg.png`,
  "RU-SAK": `${wikiHost}5/57/Flag_of_Sakhalin_Oblast.svg/100px-Flag_of_Sakhalin_Oblast.svg.png`,
  "RU-SVE": `${wikiHost}e/ef/Flag_of_Sverdlovsk_Oblast.svg/100px-Flag_of_Sverdlovsk_Oblast.svg.png`,
  "RU-SMO": `${wikiHost}f/fa/Flag_of_Smolensk_Oblast.svg/100px-Flag_of_Smolensk_Oblast.svg.png`,
  "RU-TAM": `${wikiHost}3/39/Flag_of_Tambov_Oblast.svg/100px-Flag_of_Tambov_Oblast.svg.png`,
  "RU-TVE": `${wikiHost}6/60/Flag_of_Tver_Oblast.svg/100px-Flag_of_Tver_Oblast.svg.png`,
  "RU-TOM": `${wikiHost}5/50/Flag_of_Tomsk_Oblast.svg/100px-Flag_of_Tomsk_Oblast.svg.png`,
  "RU-TUL": `${wikiHost}6/69/Flag_of_Tula_Oblast.svg/100px-Flag_of_Tula_Oblast.svg.png`,
  "RU-TYU": `${wikiHost}4/4e/Flag_of_Tyumen_Oblast.svg/100px-Flag_of_Tyumen_Oblast.svg.png`,
  "RU-ULY": `${wikiHost}d/d8/Flag_of_Ulyanovsk_Oblast.svg/100px-Flag_of_Ulyanovsk_Oblast.svg.png`,
  "RU-CHE": `${wikiHost}c/ce/Flag_of_Chelyabinsk_Oblast.svg/100px-Flag_of_Chelyabinsk_Oblast.svg.png`,
  "RU-YAR": `${wikiHost}b/ba/Flag_of_Yaroslavl_Oblast.svg/100px-Flag_of_Yaroslavl_Oblast.svg.png`,
  "RU-AD": `${wikiHost}1/16/Flag_of_Adygea.svg/100px-Flag_of_Adygea.svg.png`,
  "RU-BA": `${wikiHost}3/3d/Flag_of_Bashkortostan.svg/100px-Flag_of_Bashkortostan.svg.png`,
  "RU-BU": `${wikiHost}6/68/Flag_of_Buryatia.svg/100px-Flag_of_Buryatia.svg.png`,
  "RU-DA": `${wikiHost}c/c3/Flag_of_Dagestan.svg/100px-Flag_of_Dagestan.svg.png`,
  "RU-IN": `${wikiHost}0/00/Flag_of_Ingushetia.svg/100px-Flag_of_Ingushetia.svg.png`,
  "RU-KB": `${wikiHost}d/d8/Flag_of_Kabardino-Balkaria.svg/100px-Flag_of_Kabardino-Balkaria.svg.png`,
  "RU-KL": `${wikiHost}9/9f/Flag_of_Kalmykia.svg/100px-Flag_of_Kalmykia.svg.png`,
  "RU-KC": `${wikiHost}5/59/Flag_of_Karachay-Cherkessia.svg/100px-Flag_of_Karachay-Cherkessia.svg.png`,
  "RU-KR": `${wikiHost}6/69/Flag_of_Karelia.svg/100px-Flag_of_Karelia.svg.png`,
  "RU-ME": `${wikiHost}a/a7/Flag_of_Mari_El.svg/100px-Flag_of_Mari_El.svg.png`,
  "RU-MO": `${wikiHost}2/2f/Flag_of_Mordovia.svg/100px-Flag_of_Mordovia.svg.png`,
  "RU-AL": `${wikiHost}f/ff/Flag_of_Altai_Republic.svg/100px-Flag_of_Altai_Republic.svg.png`,
  "RU-KO": `${wikiHost}5/54/Flag_of_Komi.svg/100px-Flag_of_Komi.svg.png`,
  "RU-SA": `${wikiHost}e/eb/Flag_of_Sakha.svg/100px-Flag_of_Sakha.svg.png`,
  "RU-SE": `${wikiHost}1/1c/Flag_of_North_Ossetia.svg/100px-Flag_of_North_Ossetia.svg.png`,
  "RU-TA": `${wikiHost}2/28/Flag_of_Tatarstan.svg/100px-Flag_of_Tatarstan.svg.png`,
  "RU-TY": `${wikiHost}7/77/Flag_of_Tuva.svg/100px-Flag_of_Tuva.svg.png`,
  "RU-UD": `${wikiHost}c/c7/Flag_of_Udmurtia.svg/100px-Flag_of_Udmurtia.svg.png`,
  "RU-KK": `${wikiHost}e/ec/Flag_of_Khakassia.svg/100px-Flag_of_Khakassia.svg.png`,
  "RU-CE": `${wikiHost}1/13/Flag_of_the_Chechen_Republic.svg/100px-Flag_of_the_Chechen_Republic.svg.png`,
  "RU-CU": `${wikiHost}d/d7/Flag_of_Chuvashia.svg/100px-Flag_of_Chuvashia.svg.png`,
  "RU-ALT": `${wikiHost}4/4b/Flag_of_Altai_Krai.svg/100px-Flag_of_Altai_Krai.svg.png`,
  "RU-ZAB": `${wikiHost}b/b8/Flag_of_Zabaykalsky_Krai.svg/100px-Flag_of_Zabaykalsky_Krai.svg.png`,
  "RU-KAM": `${wikiHost}a/a7/Flag_of_Kamchatka_Krai.svg/100px-Flag_of_Kamchatka_Krai.svg.png`,
  "RU-KDA": `${wikiHost}a/a7/Flag_of_Krasnodar_Krai.svg/100px-Flag_of_Krasnodar_Krai.svg.png`,
  "RU-KYA": `${wikiHost}2/2d/Flag_of_Krasnoyarsk_Krai.svg/100px-Flag_of_Krasnoyarsk_Krai.svg.png`,
  "RU-PER": `${wikiHost}b/b5/Flag_of_Perm_Krai.svg/100px-Flag_of_Perm_Krai.svg.png`,
  "RU-PRI": `${wikiHost}3/38/Flag_of_Primorsky_Krai.svg/100px-Flag_of_Primorsky_Krai.svg.png`,
  "RU-STA": `${wikiHost}b/b4/Flag_of_Stavropol_Krai.svg/100px-Flag_of_Stavropol_Krai.svg.png`,
  "RU-KHA": `${wikiHost}4/4f/Flag_of_Khabarovsk_Krai.svg/100px-Flag_of_Khabarovsk_Krai.svg.png`,
  "RU-NEN": `${wikiHost}1/15/Flag_of_Nenets_Autonomous_District.svg/100px-Flag_of_Nenets_Autonomous_District.svg.png`,
  "RU-KHM": `${wikiHost}7/70/Flag_of_Yugra.svg/100px-Flag_of_Yugra.svg.png`,
  "RU-CHU": `${wikiHost}a/a0/Flag_of_Chukotka.svg/100px-Flag_of_Chukotka.svg.png`,
  "RU-YAN": `${wikiHost}c/c7/Flag_of_Yamal-Nenets_Autonomous_District.svg/100px-Flag_of_Yamal-Nenets_Autonomous_District.svg.png`,
  "RU-SPE": `${wikiHost}c/c9/Flag_of_Saint_Petersburg_%28digital_version%29.svg/100px-Flag_of_Saint_Petersburg_%28digital_version%29.svg.png`,
  "RU-MOW": `${wikiHost}0/03/Flag_of_Moscow%2C_Russia.svg/100px-Flag_of_Moscow%2C_Russia.svg.png`,
  "RU-YEV": `${wikiHost}0/0e/Flag_of_the_Jewish_Autonomous_Oblast.svg/100px-Flag_of_the_Jewish_Autonomous_Oblast.svg.png`,
  "RU-SEV": `${wikiHost}1/14/Flag_of_Sevastopol.svg/100px-Flag_of_Sevastopol.svg.png`,
  "RU-KRY": `${wikiHost}a/aa/Flag_of_Crimea.svg/100px-Flag_of_Crimea.svg.png`,
};

function Flag({ iso3166, style, className }) {
  const FlagIn = flags[iso3166];
  const FlagRussiaIn = ruIconsMap[iso3166];
  if (FlagRussiaIn)
    return <img src={FlagRussiaIn} style={style} className={className} />;
  if (FlagIn) return <FlagIn style={style} className={className} />;
  return <div style={style} className={className}></div>;
}

export default Flag;
